// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ClstElementV: typeof import('./src/components/ClstElementV.vue')['default']
    ClusterSelectTopV: typeof import('./src/components/ClusterSelectTopV.vue')['default']
    ClustersV: typeof import('./src/components/ClustersV.vue')['default']
    DividerV: typeof import('./src/components/DividerV.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
